import { Product } from "../types/product.type";

const DATA: Product[] = [
    {
        id: "1",
        name: "Wireless Headphones",
        price: "$89.99",
        quality: 4,
        description: "High-quality wireless headphones with noise-cancellation and long battery life.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "2",
        name: "Smartphone Stand",
        price: "$14.99",
        quality: 3,
        description: "Adjustable stand for smartphones, suitable for both home and office use.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "3",
        name: "Bluetooth Speaker",
        price: "$49.99",
        quality: 5,
        description: "Compact Bluetooth speaker with excellent sound quality and a durable build.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "4",
        name: "Gaming Mouse",
        price: "$29.99",
        quality: 4,
        description: "Ergonomic gaming mouse with customizable buttons and RGB lighting.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "5",
        name: "Laptop Cooling Pad",
        price: "$19.99",
        quality: 3,
        description: "Efficient cooling pad to prevent your laptop from overheating during extended use.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "6",
        name: "USB-C Hub",
        price: "$24.99",
        quality: 4,
        description: "Multiport USB-C hub with HDMI, USB 3.0, and SD card slots.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "7",
        name: "4K Monitor",
        price: "$299.99",
        quality: 5,
        description: "High-resolution 4K monitor with vivid colors and HDR support.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "8",
        name: "Wireless Keyboard",
        price: "$34.99",
        quality: 4,
        description: "Slim and portable wireless keyboard with a long battery life.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "9",
        name: "External Hard Drive",
        price: "$59.99",
        quality: 4,
        description: "1TB external hard drive with fast data transfer and durable design.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "10",
        name: "Smart Home Camera",
        price: "$89.99",
        quality: 4,
        description: "Wi-Fi enabled smart camera with night vision and two-way audio.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "11",
        name: "Portable Charger",
        price: "$19.99",
        quality: 3,
        description: "Compact 10,000mAh portable charger with dual USB ports.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "12",
        name: "Fitness Tracker",
        price: "$59.99",
        quality: 4,
        description: "Waterproof fitness tracker with heart rate monitor and GPS.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "13",
        name: "VR Headset",
        price: "$199.99",
        quality: 5,
        description: "Immersive VR headset compatible with popular gaming systems.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "14",
        name: "Mechanical Keyboard",
        price: "$79.99",
        quality: 4,
        description: "Tactile mechanical keyboard with customizable backlighting.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "15",
        name: "Wireless Mouse",
        price: "$19.99",
        quality: 3,
        description: "Responsive wireless mouse with ergonomic design and adjustable DPI.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "16",
        name: "Portable Projector",
        price: "$249.99",
        quality: 4,
        description: "Mini projector with 1080p resolution and built-in speakers.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "17",
        name: "Tablet Stand",
        price: "$14.99",
        quality: 4,
        description: "Stable and adjustable tablet stand for hands-free viewing.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "18",
        name: "Noise-Canceling Earbuds",
        price: "$39.99",
        quality: 5,
        description: "Compact and comfortable earbuds with active noise cancellation.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "19",
        name: "Smart Light Bulb",
        price: "$12.99",
        quality: 4,
        description: "Smart light bulb compatible with voice assistants, adjustable brightness.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "20",
        name: "HD Webcam",
        price: "$29.99",
        quality: 4,
        description: "1080p HD webcam with built-in microphone for clear video calls.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "21",
        name: "Gaming Headset",
        price: "$59.99",
        quality: 4,
        description: "Comfortable gaming headset with surround sound and noise-canceling microphone.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "22",
        name: "Smart Thermostat",
        price: "$99.99",
        quality: 5,
        description: "Energy-saving smart thermostat compatible with voice assistants.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "23",
        name: "Digital Notepad",
        price: "$34.99",
        quality: 3,
        description: "Eco-friendly digital notepad with a stylus for paperless note-taking.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "24",
        name: "Adjustable Desk Lamp",
        price: "$24.99",
        quality: 4,
        description: "LED desk lamp with adjustable brightness and color temperature.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "25",
        name: "Wireless Charger",
        price: "$19.99",
        quality: 4,
        description: "Fast wireless charger compatible with most smartphones.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "26",
        name: "Portable SSD",
        price: "$129.99",
        quality: 5,
        description: "500GB portable SSD with ultra-fast transfer speeds and durable design.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "27",
        name: "Smart Scale",
        price: "$29.99",
        quality: 3,
        description: "Digital smart scale with body composition analysis and app support.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "28",
        name: "Laptop Backpack",
        price: "$49.99",
        quality: 4,
        description: "Durable backpack with compartments for a laptop and accessories.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "29",
        name: "Digital Alarm Clock",
        price: "$19.99",
        quality: 3,
        description: "LED alarm clock with USB charging port and adjustable brightness.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
    {
        id: "30",
        name: "Robot Vacuum Cleaner",
        price: "$249.99",
        quality: 5,
        description: "Smart robot vacuum cleaner with Wi-Fi connectivity and remote control.",
        imageUrl: "https://th.bing.com/th/id/OIG2.9O4YqGf98tiYzjKDvg7L",
    },
];

export default DATA;
